### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by skymandr**
This adds issue templates, which might be helpful.

### CODE REVIEW

**Review by pzaino — COMMENTED** [review]
Can we please add also:

RISC OS release: ''

Modules list: '' (optional)

System model: '' (like Rpi 3B+, iYONIX etc...)

Not sure if we may need anything else, given that there is going to be compiled code maybe asking for the version of SharedCLib?

**Comment by skymandr** [comment]
> Can we please add also:

I'll fix it right away. Feel free to use "Request changes" for this kind of thing. It blocks merging but it is much clearer in my opinion. It is not an unkind thing to do, as far as I'm concerned.

Would you like to see this in the other PR:s I made as well?

**Comment by skymandr** [comment]
I've added a template, but note that it is an _issue template_, not a _release template_, which I suspect is what you meant. If that is indeed what you wanted, I'm not entirely sure how to add it, but I can ask a co-worker tomorrow. Let me know!

**Comment by pzaino** [comment]
I meant issue template. The reason for asking which RISC OS release, modules list etc... is because historically different releases of RISC OS can present different behaviours, modules can affect overall functionalities so it's always a good practice to collect such type of info when reporting an issue with our code. And yes different RISC OS platform can behave different... for example FAT32 can handle up to 2T discs if used via SCSIFS, but if used via FileSwitch then has the same limitations as FileCore 256GB (I am sure that people would still argue with me about this, but if they go and actually test it then the "secret" would be revealed!!!!) 🤣

**Review by pzaino — APPROVED** [review]
Looks good to me, thanks for the changes!

**Pull request merged**
